### ISSUE TITLE
Pick a new name for the package

### ISSUE THREAD

**Issue by kelly-sovacool** [SchlossLab/mothuR#23]
Requirements:
1. Pat has to like it.
    - Pat definitely won't like it if it has mixed case.
1. There are no other requirements.

**Comment by kelly-sovacool** [comment]
Possibilities submitted by labbies in Slack:

## mothur-related

- mothurr
- mothurer: mother your mothur data
- grandmothur
- nanny: mothur's assistant
- cranmothur
- r.mothur
- tidymothur
- stepmothur: next steps of your mothur analysis
- mothur2r

## lab-related

- schlossur
- schtools: Schloss Lab tools for reproducible microbiome research 💩

**Comment by courtneyarmour** [comment]
I second schtools!

**Comment by pschloss** [comment]
schtools sounds good to me - I think most of the functions in the package are likely to be mothur-independent so let's not mix names
